### ISSUE TITLE
Group reviews by year

### ISSUE THREAD

**Issue by JunaidQadirB** [Elhebert/a-year-review#16]
It would be super useful if there were a key for the year in `reviews.json` for future(or past) reviews.
This is what I think would be enough:
```json
  {
    "author": "Freek Van der Herten",
    "link": "https://freek.dev/1522-a-recap-of-2019",
    "year": "2019"
  }
```

**Comment by Elhebert** [comment]
All previous years' websites are still maintained and available. I have a branch per year which has its own subdomain.

So for the 2018 reviews: https://2018.a-year-review.tech
And next year the 2019 reviews will be available at https://2019.a-year-review.tech

I prefer to have one website per year as it allows me to change the whole tech stack each year if I want to test another solution.

I do agree that a way to switch year would be great 🤔 Maybe I'll add a dropdown in the header or something similar.

**Comment by JunaidQadirB** [comment]
Ok, I didn't know that you have reviews from previous year(s). Yea a dropdown would help.

**Comment by Elhebert** [comment]
FYI: I added a switcher in https://github.com/Elhebert/a-year-review/commit/0d7fc890419555f661c50c2d56e64161d6c496eb
